#!/usr/bin/env python3
"""Prepare Casdoor MySQL dumps for AI Sphere Auth bootstrap.

The tool is intentionally dependency-free so it can run on an ops box that only has
Python 3. It supports two modes:

- full: normalize a full mysqldump by removing environment-specific statements
  such as GTID_PURGED, CREATE DATABASE and USE.
- data-only: extract rows related to AI Sphere / SkillHub and emit REPLACE INTO
  statements that can be imported into an existing Casdoor database.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Iterable

DEFAULT_KEYWORDS = ["aisphere", "skillhub"]
DEFAULT_TABLES = [
    "organization",
    "application",
    "model",
    "permission",
    "permission_rule",
    "role",
    "group",
    "adapter",
    "enforcer",
]
OPTIONAL_USER_TABLES = ["user"]
SKIP_TABLES = {"token", "session", "record", "ticket", "verification_record"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Prepare a Casdoor mysqldump for AI Sphere Auth import.",
    )
    parser.add_argument("--input", required=True, help="Source Casdoor SQL dump")
    parser.add_argument("--output", required=True, help="Prepared SQL output path")
    parser.add_argument(
        "--mode",
        choices=["full", "data-only"],
        default="data-only",
        help="Preparation mode. full keeps schema/data but strips environment-specific statements; data-only extracts AI Sphere rows.",
    )
    parser.add_argument(
        "--keywords",
        default=",".join(DEFAULT_KEYWORDS),
        help="Comma-separated row match keywords for data-only mode. Default: aisphere,skillhub",
    )
    parser.add_argument(
        "--tables",
        default=",".join(DEFAULT_TABLES),
        help="Comma-separated table allowlist for data-only mode.",
    )
    parser.add_argument(
        "--include-users",
        action="store_true",
        help="Also extract matched users. This may include password hashes and should be used deliberately.",
    )
    parser.add_argument(
        "--no-strip-locks",
        action="store_true",
        help="Keep LOCK TABLES / UNLOCK TABLES in full mode. By default they are stripped to reduce privilege requirements.",
    )
    return parser.parse_args()


def strip_mysql_dump_boilerplate(sql: str, strip_locks: bool = True) -> str:
    """Remove statements that commonly break imports into managed MySQL."""
    out: list[str] = []
    for line in sql.splitlines():
        stripped = line.strip()
        upper = stripped.upper()
        if "GTID_PURGED" in upper:
            continue
        if "SQL_LOG_BIN" in upper:
            continue
        if upper.startswith("CREATE DATABASE ") or upper.startswith("CREATE DATABASE /*!32312"):
            continue
        if upper.startswith("USE `") or upper.startswith("USE "):
            continue
        if upper.startswith("DROP DATABASE"):
            continue
        if strip_locks and (upper.startswith("LOCK TABLES") or upper.startswith("UNLOCK TABLES")):
            continue
        out.append(line)
    return "\n".join(out).rstrip() + "\n"


def find_insert_statement(sql: str, table: str) -> str | None:
    pattern = re.compile(rf"INSERT INTO `{re.escape(table)}` VALUES (.*?);\n", re.S)
    match = pattern.search(sql)
    if not match:
        return None
    return match.group(1).strip()


def split_insert_rows(values: str) -> list[str]:
    rows: list[str] = []
    depth = 0
    start: int | None = None
    in_quote = False
    escaped = False
    for idx, ch in enumerate(values):
        if in_quote:
            if escaped:
                escaped = False
            elif ch == "\\":
                escaped = True
            elif ch == "'":
                in_quote = False
            continue

        if ch == "'":
            in_quote = True
        elif ch == "(":
            if depth == 0:
                start = idx
            depth += 1
        elif ch == ")":
            depth -= 1
            if depth == 0 and start is not None:
                rows.append(values[start : idx + 1])
                start = None
    return rows


def contains_keyword(row: str, keywords: Iterable[str]) -> bool:
    lowered = row.lower()
    return any(keyword in lowered for keyword in keywords)


def build_data_only_sql(sql: str, tables: list[str], keywords: list[str], include_users: bool) -> tuple[str, dict[str, int]]:
    allowed_tables = list(tables)
    if include_users:
        allowed_tables.extend(OPTIONAL_USER_TABLES)

    lines: list[str] = [
        "-- AI Sphere / SkillHub Casdoor data-only bootstrap SQL",
        "-- Generated by scripts/casdoor/prepare-casdoor-sql.py",
        "-- This file intentionally excludes volatile tables such as token/session/record.",
        "SET FOREIGN_KEY_CHECKS=0;",
        "",
    ]
    summary: dict[str, int] = {}

    for table in allowed_tables:
        if table in SKIP_TABLES:
            continue
        values = find_insert_statement(sql, table)
        if not values:
            continue
        rows = split_insert_rows(values)
        matched = [row for row in rows if contains_keyword(row, keywords)]
        if not matched:
            continue
        summary[table] = len(matched)
        lines.append(f"-- table: {table}, rows: {len(matched)}")
        for row in matched:
            lines.append(f"REPLACE INTO `{table}` VALUES {row};")
        lines.append("")

    lines.extend(["SET FOREIGN_KEY_CHECKS=1;", ""])
    return "\n".join(lines), summary


def main() -> int:
    args = parse_args()
    input_path = Path(args.input)
    output_path = Path(args.output)

    if not input_path.is_file():
        print(f"[ERROR] input SQL not found: {input_path}", file=sys.stderr)
        return 1

    sql = input_path.read_text(encoding="utf-8", errors="replace")
    output_path.parent.mkdir(parents=True, exist_ok=True)

    if args.mode == "full":
        prepared = strip_mysql_dump_boilerplate(sql, strip_locks=not args.no_strip_locks)
        output_path.write_text(prepared, encoding="utf-8")
        print(f"[OK] wrote normalized full dump: {output_path}")
        print("[INFO] stripped GTID_PURGED, SQL_LOG_BIN, CREATE DATABASE, USE and lock statements")
        return 0

    keywords = [item.strip().lower() for item in args.keywords.split(",") if item.strip()]
    tables = [item.strip() for item in args.tables.split(",") if item.strip()]
    if not keywords:
        print("[ERROR] at least one keyword is required in data-only mode", file=sys.stderr)
        return 1
    if not tables:
        print("[ERROR] at least one table is required in data-only mode", file=sys.stderr)
        return 1

    prepared, summary = build_data_only_sql(sql, tables, keywords, include_users=args.include_users)
    output_path.write_text(prepared, encoding="utf-8")
    print(f"[OK] wrote data-only bootstrap SQL: {output_path}")
    if summary:
        print("[INFO] extracted rows:")
        for table, count in sorted(summary.items()):
            print(f"  - {table}: {count}")
    else:
        print("[WARN] no matching rows found. Check --keywords and --tables.")
    if args.include_users:
        print("[WARN] --include-users may copy password hashes; review output before import.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
