#!/usr/bin/env bash
set -euo pipefail

export AISPHERE_SESSION_PROVIDER="${AISPHERE_SESSION_PROVIDER:-redis}"
export AISPHERE_REDIS_ADDRS="${AISPHERE_REDIS_ADDRS:-127.0.0.1:6379}"
export AISPHERE_REDIS_PREFIX="${AISPHERE_REDIS_PREFIX:-aisphere}"
export AISPHERE_SERVICE_TOKEN_REQUIRED="${AISPHERE_SERVICE_TOKEN_REQUIRED:-true}"
export AISPHERE_SERVICE_TOKEN="${AISPHERE_SERVICE_TOKEN:-dev-service-token-change-me-please-rotate}"
export AISPHERE_SERVICE_TOKEN_HEADER="${AISPHERE_SERVICE_TOKEN_HEADER:-X-Aisphere-Service-Token}"
export AISPHERE_INTERNAL_RATE_LIMIT_ENABLED="${AISPHERE_INTERNAL_RATE_LIMIT_ENABLED:-true}"
export AISPHERE_INTERNAL_RATE_LIMIT_QPS="${AISPHERE_INTERNAL_RATE_LIMIT_QPS:-100}"
export AISPHERE_INTERNAL_RATE_LIMIT_BURST="${AISPHERE_INTERNAL_RATE_LIMIT_BURST:-200}"

go run ./cmd/server
