$ErrorActionPreference = "Stop"

if (-not $env:AISPHERE_SESSION_PROVIDER) { $env:AISPHERE_SESSION_PROVIDER = "redis" }
if (-not $env:AISPHERE_REDIS_ADDRS) { $env:AISPHERE_REDIS_ADDRS = "127.0.0.1:6379" }
if (-not $env:AISPHERE_REDIS_PREFIX) { $env:AISPHERE_REDIS_PREFIX = "aisphere" }
if (-not $env:AISPHERE_SERVICE_TOKEN_REQUIRED) { $env:AISPHERE_SERVICE_TOKEN_REQUIRED = "true" }
if (-not $env:AISPHERE_SERVICE_TOKEN) { $env:AISPHERE_SERVICE_TOKEN = "dev-service-token-change-me-please-rotate" }
if (-not $env:AISPHERE_SERVICE_TOKEN_HEADER) { $env:AISPHERE_SERVICE_TOKEN_HEADER = "X-Aisphere-Service-Token" }
if (-not $env:AISPHERE_INTERNAL_RATE_LIMIT_ENABLED) { $env:AISPHERE_INTERNAL_RATE_LIMIT_ENABLED = "true" }
if (-not $env:AISPHERE_INTERNAL_RATE_LIMIT_QPS) { $env:AISPHERE_INTERNAL_RATE_LIMIT_QPS = "100" }
if (-not $env:AISPHERE_INTERNAL_RATE_LIMIT_BURST) { $env:AISPHERE_INTERNAL_RATE_LIMIT_BURST = "200" }

go run ./cmd/server
