#!/usr/bin/env bash
set -euo pipefail

export AISPHERE_SESSION_PROVIDER="${AISPHERE_SESSION_PROVIDER:-redis}"
export AISPHERE_REDIS_ADDRS="${AISPHERE_REDIS_ADDRS:-127.0.0.1:6379}"
export AISPHERE_REDIS_PREFIX="${AISPHERE_REDIS_PREFIX:-aisphere}"
export AISPHERE_SERVICE_TOKEN_REQUIRED="${AISPHERE_SERVICE_TOKEN_REQUIRED:-true}"
export AISPHERE_SERVICE_TOKEN="${AISPHERE_SERVICE_TOKEN:-dev-service-token-change-me}"
export AISPHERE_SERVICE_TOKEN_HEADER="${AISPHERE_SERVICE_TOKEN_HEADER:-X-Aisphere-Service-Token}"

go run ./cmd/server
